### PR TITLE
Add pyproject.toml

### PR DESCRIPTION
**Pull request by externl**
Adds support for https://github.com/zeroc-ice/ice/issues/1414

### CODE REVIEW

**Review by pepone — APPROVED** [review]
Is that all that is required?

Shouldn't we also move some of the setup.py settings to this `pyproject.toml` file?
name/version/author/classifier/...

**Comment by externl** [comment]
Lots of examples I see have all this stuff (name, version, etc.)  in `setup.cfg`. For some reason we put it all in `setup.py`. For some reason ours is empty. For example https://github.com/pyca/cryptography/blob/main/setup.cfg. Did you see anything saying `pyproject.toml` is the recommend place now?

**Comment by pepone** [comment]
> Lots of examples I see have all this stuff (name, version, etc.) in setup.cfg

Not sure what is the recommended way to do that, poetry put this in the pyproject.toml file

https://github.com/python-poetry/poetry/blob/master/pyproject.toml

**Comment by externl** [comment]
That's all under the `[tool.poetry]` section. So I think it's only relevant if you're using the poetry tool.

**Pull request merged**
